
#spring.h2.console.settings.web-allow-others=true        //进行该配置后，h2 web consloe就可以在远程访问了。否则只能在本机访问。
#spring.h2.console.path=/h2-console                      //进行该配置，你就可以通过YOUR_URL/h2-console访问h2 web consloe。YOUR_URL是你程序的访问URl。
#spring.h2.console.enabled=true                   //进行该配置，程序开启时就会启动h2 web consloe。当然这是默认的，如果你不想在启动程序时启动h2 web consloe，那么就设置为false。
spring:
  jpa:
    database: mysql
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
#  datasource:
#    #  spring.datasource.driverClassName = com.mysql.jdbc.Driver
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/scd
#    name: root
#    password: root

  #    定制注册服务名称
  application:
    name: hnydjy-tcqzt
logging:
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace
    com.itmuch: debug
server:
  port: 8081